# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: saturnin/protobuf/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='saturnin/protobuf/common.proto',
  package='saturnin.protobuf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1esaturnin/protobuf/common.proto\x12\x11saturnin.protobuf\x1a\x1cgoogle/protobuf/struct.proto\"L\n\x11GenericDataRecord\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"K\n\x12GenericDataPackage\x12\x35\n\x07records\x18\x01 \x03(\x0b\x32$.saturnin.protobuf.GenericDataRecord*\xd3\x01\n\x0fServiceTypeEnum\x12\x14\n\x10SVC_TYPE_UNKNOWN\x10\x00\x12\x1a\n\x16SVC_TYPE_DATA_PROVIDER\x10\x01\x12\x18\n\x14SVC_TYPE_DATA_FILTER\x10\x02\x12\x1a\n\x16SVC_TYPE_DATA_CONSUMER\x10\x03\x12\x17\n\x13SVC_TYPE_PROCESSING\x10\x04\x12\x15\n\x11SVC_TYPE_EXECUTOR\x10\x05\x12\x14\n\x10SVC_TYPE_CONTROL\x10\x06\x12\x12\n\x0eSVC_TYPE_OTHER\x10\x64*y\n\rSeverityLevel\x12\x14\n\x10SEVERITY_UNKNOWN\x10\x00\x12\x11\n\rSEVERITY_INFO\x10\x01\x12\x14\n\x10SEVERITY_WARNING\x10\x02\x12\x12\n\x0eSEVERITY_ERROR\x10\x03\x12\x15\n\x11SEVERITY_CRITICAL\x10\x04\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])

_SERVICETYPEENUM = _descriptor.EnumDescriptor(
  name='ServiceTypeEnum',
  full_name='saturnin.protobuf.ServiceTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_DATA_PROVIDER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_DATA_FILTER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_DATA_CONSUMER', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_PROCESSING', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_EXECUTOR', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_CONTROL', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SVC_TYPE_OTHER', index=7, number=100,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=239,
  serialized_end=450,
)
_sym_db.RegisterEnumDescriptor(_SERVICETYPEENUM)

ServiceTypeEnum = enum_type_wrapper.EnumTypeWrapper(_SERVICETYPEENUM)
_SEVERITYLEVEL = _descriptor.EnumDescriptor(
  name='SeverityLevel',
  full_name='saturnin.protobuf.SeverityLevel',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SEVERITY_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEVERITY_INFO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEVERITY_WARNING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEVERITY_ERROR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEVERITY_CRITICAL', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=452,
  serialized_end=573,
)
_sym_db.RegisterEnumDescriptor(_SEVERITYLEVEL)

SeverityLevel = enum_type_wrapper.EnumTypeWrapper(_SEVERITYLEVEL)
SVC_TYPE_UNKNOWN = 0
SVC_TYPE_DATA_PROVIDER = 1
SVC_TYPE_DATA_FILTER = 2
SVC_TYPE_DATA_CONSUMER = 3
SVC_TYPE_PROCESSING = 4
SVC_TYPE_EXECUTOR = 5
SVC_TYPE_CONTROL = 6
SVC_TYPE_OTHER = 100
SEVERITY_UNKNOWN = 0
SEVERITY_INFO = 1
SEVERITY_WARNING = 2
SEVERITY_ERROR = 3
SEVERITY_CRITICAL = 4



_GENERICDATARECORD = _descriptor.Descriptor(
  name='GenericDataRecord',
  full_name='saturnin.protobuf.GenericDataRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='saturnin.protobuf.GenericDataRecord.sequence', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='saturnin.protobuf.GenericDataRecord.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=159,
)


_GENERICDATAPACKAGE = _descriptor.Descriptor(
  name='GenericDataPackage',
  full_name='saturnin.protobuf.GenericDataPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='saturnin.protobuf.GenericDataPackage.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=236,
)

_GENERICDATARECORD.fields_by_name['data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GENERICDATAPACKAGE.fields_by_name['records'].message_type = _GENERICDATARECORD
DESCRIPTOR.message_types_by_name['GenericDataRecord'] = _GENERICDATARECORD
DESCRIPTOR.message_types_by_name['GenericDataPackage'] = _GENERICDATAPACKAGE
DESCRIPTOR.enum_types_by_name['ServiceTypeEnum'] = _SERVICETYPEENUM
DESCRIPTOR.enum_types_by_name['SeverityLevel'] = _SEVERITYLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericDataRecord = _reflection.GeneratedProtocolMessageType('GenericDataRecord', (_message.Message,), {
  'DESCRIPTOR' : _GENERICDATARECORD,
  '__module__' : 'saturnin.protobuf.common_pb2'
  # @@protoc_insertion_point(class_scope:saturnin.protobuf.GenericDataRecord)
  })
_sym_db.RegisterMessage(GenericDataRecord)

GenericDataPackage = _reflection.GeneratedProtocolMessageType('GenericDataPackage', (_message.Message,), {
  'DESCRIPTOR' : _GENERICDATAPACKAGE,
  '__module__' : 'saturnin.protobuf.common_pb2'
  # @@protoc_insertion_point(class_scope:saturnin.protobuf.GenericDataPackage)
  })
_sym_db.RegisterMessage(GenericDataPackage)


# @@protoc_insertion_point(module_scope)
