# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: saturnin/core/protobuf/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#saturnin/core/protobuf/common.proto\x12\x16saturnin.core.protobuf\x1a\x1cgoogle/protobuf/struct.proto\"L\n\x11GenericDataRecord\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"P\n\x12GenericDataPackage\x12:\n\x07records\x18\x01 \x03(\x0b\x32).saturnin.core.protobuf.GenericDataRecord*\xd3\x01\n\x0fServiceTypeEnum\x12\x14\n\x10SVC_TYPE_UNKNOWN\x10\x00\x12\x1a\n\x16SVC_TYPE_DATA_PROVIDER\x10\x01\x12\x18\n\x14SVC_TYPE_DATA_FILTER\x10\x02\x12\x1a\n\x16SVC_TYPE_DATA_CONSUMER\x10\x03\x12\x17\n\x13SVC_TYPE_PROCESSING\x10\x04\x12\x15\n\x11SVC_TYPE_EXECUTOR\x10\x05\x12\x14\n\x10SVC_TYPE_CONTROL\x10\x06\x12\x12\n\x0eSVC_TYPE_OTHER\x10\x64*y\n\rSeverityLevel\x12\x14\n\x10SEVERITY_UNKNOWN\x10\x00\x12\x11\n\rSEVERITY_INFO\x10\x01\x12\x14\n\x10SEVERITY_WARNING\x10\x02\x12\x12\n\x0eSEVERITY_ERROR\x10\x03\x12\x15\n\x11SEVERITY_CRITICAL\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'saturnin.core.protobuf.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVICETYPEENUM._serialized_start=254
  _SERVICETYPEENUM._serialized_end=465
  _SEVERITYLEVEL._serialized_start=467
  _SEVERITYLEVEL._serialized_end=588
  _GENERICDATARECORD._serialized_start=93
  _GENERICDATARECORD._serialized_end=169
  _GENERICDATAPACKAGE._serialized_start=171
  _GENERICDATAPACKAGE._serialized_end=251
# @@protoc_insertion_point(module_scope)
